name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: echo "Workflow passed"
